import bs4
import os
import requests
from bs4 import BeautifulSoup
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Crawler
base_url = "https://nvidia.github.io/cuda-quantum/0.7.0/"
entry_url = f"{base_url}using/quick_start.html"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
input_dir = "cuda_quantum_full_docs"
output_dir = os.path.join(input_dir, "splits")

def get_all_links(url):
    print(f"Analyzing navigation bar: {url}")
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    sidebar = soup.select_one(".bd-sidebar") or soup.select_one("nav")
    links = []
    if sidebar:
        for a in sidebar.find_all('a', href=True):
            full_url = requests.compat.urljoin(url, a['href']).split('#')[0]
           
            if full_url.startswith(base_url) and full_url.endswith(".html"):
                if full_url not in links:
                    links.append(full_url)
    return sorted(list(set(links)))

def scrape_docs():
    try:
        all_pages = get_all_links(entry_url)
        print(f"Found {len(all_pages)} page links in total.")
        
        bs4_strainer = bs4.SoupStrainer(attrs={"itemprop": "articleBody"})
        loader = WebBaseLoader(
            web_paths=all_pages,
            bs_kwargs={"parse_only": bs4_strainer},
            header_template=headers
        )

        print("\nStarting full download of all content...")
        docs = loader.load()

        if not os.path.exists(input_dir):
            os.makedirs(input_dir)

        for i, doc in enumerate(docs):
            relative_path = all_pages[i].replace(base_url, "").replace("/", "_").replace(".html", "")
            if not relative_path: relative_path = "index"
            
            filename = os.path.join(input_dir, f"{relative_path}.txt")
            with open(filename, "w", encoding="utf-8") as f:
                f.write(doc.page_content.strip())
            
        print(f"\n Finished! Crawled files saved to: {input_dir}")

    except Exception as e:
        print(f"Crawler error: {e}")
# Split
def process_and_split_documents():
    if not os.path.exists(input_dir):
        print(f"Directory {input_dir} not found")
        return
    # Create metadata to facilitate source tracing 
    text_splitter = RecursiveCharacterTextSplitter(
        # To avoid breaking code like cudaq.kernel, change "." to ". " (period + space) 
        # Ensure chunking only happens at the end of a sentence or a newline
        separators=["\n\n", "\n", "。 ", ". ", " ", ""],
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )

    all_docs = []
    metadatas = []
    files_processed = 0

    print(f"\nLoading documents from '{input_dir}'...")
    for filename in os.listdir(input_dir):
        if filename.endswith(".txt"):
            filepath = os.path.join(input_dir, filename)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    # Read full text and remove the regression marker "¶" generated by Sphinx
                    content = f.read().replace("¶", "")
                
                if not content.strip():
                    continue

                all_docs.append(content)
                source_name = filename.replace(".txt", "")
                metadatas.append({"source": source_name})
                files_processed += 1
                
            except Exception as e:
                print(f"Error reading file {filename}: {e}")

    if not all_docs:
        print("No .txt files found or all documents are empty.")
        return
        
    print(f"Successfully loaded {files_processed} documents.")
    print("Performing text splitting...")
    
    splits = text_splitter.create_documents(all_docs, metadatas=metadatas)
    print(f"Splitting complete, generated {len(splits)} text chunks.")

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print("Saving files...")
    for i, split in enumerate(splits):
        source_name = split.metadata.get("source", "unknown")
        chunk_filepath = os.path.join(output_dir, f"{source_name}_chunk_{i}.txt")
        
        with open(chunk_filepath, "w", encoding="utf-8") as f:
            f.write(split.page_content)

    print(f"Execution finished! Split files saved to: {output_dir}")

if __name__ == "__main__":
    # Only execute crawler if folder doesn't exist or has no txt files
    if not os.path.exists(input_dir) or not any(fname.endswith('.txt') for fname in os.listdir(input_dir)):
        print("No downloaded data detected, starting crawler...")
        scrape_docs()
    else:
        print(f"Data detected in '{input_dir}', skipping crawler and proceeding to text splitting!")
    
    process_and_split_documents()
